spring:
  kafka:
    properties:
      security:
        protocol: SASL_SSL
      bootstrap:
        servers: <INSERT CONFLUENT CLOUD ENDPOINT HERE>:9092
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='<CONFLUENT CLOUD API KEY>' password='<CONFLUENT CLOUD API SECRET>';
        mechanism: PLAIN


